### ISSUE TITLE
Contact request simplification

### ISSUE THREAD

**Issue by labs-dlugo** [shocknet/Lightning.Pub#384]
If the contact request is updated to also include the feed id for the recipient's side, that can be directly used to detect the request was accepted.

Prevents detection of acceptance by 3rd parties and simplifies the architecture eschewing the need for the "onAcceptedRequests" `job`.

**Comment by danlugo92** [comment]
Save the `Incoming` id, inside the corresponding `Outgoing`. Eliminates the need for the `pubToIncoming` map. Tolerate dupe chats but less prone to failure system.

**Comment by capitalistdog** [comment]
moving to nostr
