### ISSUE TITLE
API/Wallet version mismatch detection

### ISSUE THREAD

**Issue by labs-dlugo** [shocknet/Lightning.Pub#70]
- Use `package.json`'s major version digit. We are not using that digit for anything else since it's not a library.
- Obviously respect Semantic Versioning from now on.
- If API's major version digit does not match wallet's, reject the connection.

I did explore some Wallet/API version matching through `api-schema.ts` in `shock-common`. Allows for more granular control but would require better GIT discipline (so shock-common v2 can get a non-breaking fix that also shock-common v3 gets).

Still not sure which path is better but API versions are a thing since always.

Lots of authorities do recommend API versioning through a header and not through URLs (e.g. `foo.com/v1/posts`) and I think it's a good fit (and easier to implement) for our use case.

**Comment by capitalistdog** [comment]
new api
