### ISSUE TITLE
Bring tests to this repo, cover SEA.encrypt/secret/decrypt

### ISSUE THREAD

**Issue by labs-dlugo** [shocknet/Lightning.Pub#80]

**Comment by erbesharat** [comment]
Currently, there are tests in two repositories:
1. https://github.com/shocknet/api-tests
2. https://github.com/danlugo92/gun-fork-test

As far as I understood the `api-tests` repo covers SEA and encryption. It also uses a manager script in Go to manage the testing containers. So, should we bring all the tests and the manager-script to this repo? Or use the code from those repos to add unit tests in this repo and maintain the e2e tests in `api-tests`?
@boufni95 It Would be awesome to hear your thoughts too.

**Comment by capitalistdog** [comment]
`api-tests` actually tests the api's interaction with the underlying services, including LND, whereas the `fork-test` is to emulate the api actions of gun specifically- such that we can check upgrades.

> Or use the code from those repos to add unit tests in this repo and maintain the e2e tests in api-tests?

This, and also need to add coverage for our uses (with hops) upstream into gun's panic tests. `fork-test` doesn't yet test encryption, and should.

**Comment by capitalistdog** [comment]
moving to nostr
